geekshop/adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path('^user/create/$', adminapp.AdminShopUserCreateView.as_view(), name='user_create'),
    re_path('^users/read/$', adminapp.UsersListView.as_view(), name='index'),
    re_path('^user/update/(?P<pk>\d+)/$', adminapp.AdminShopUserUpdateView.as_view(), name='user_update'),
    re_path('^user/delete/(?P<pk>\d+)/$', adminapp.AdminShopUserDeleteView.as_view(), name='user_delete'),
    re_path('^user/activate/(?P<pk>\d+)/$', adminapp.AdminShopUserActivateView.as_view(), name='user_activate'),

    re_path('^categories/$', adminapp.ProductCategoryListView.as_view(), name='categories'),
    re_path('^category/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    re_path('^category/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    re_path('^category/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),
    re_path('^category/activate/(?P<pk>\d+)/$', adminapp.ProductCategoryActivateView.as_view(), name='category_activate'),

    re_path('^products/category/(?P<pk>\d+)/$', adminapp.ProductListView.as_view(), name='products'),
    re_path('^products/category/(?P<pk>\d+)/page/(?P<page>\d+)/$', adminapp.ProductListView.as_view(), name='products'),
    re_path('^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
    re_path('^product/create/(?P<pk>\d+)/$', adminapp.ProductCreateView.as_view(), name='product_create'),
    re_path('^product/update/(?P<pk>\d+)/$', adminapp.ProductUpdateView.as_view(), name='product_update'),
    re_path('^product/delete/(?P<pk>\d+)/$', adminapp.ProductDeleteView.as_view(), name='product_delete'),
    re_path('^product/activate/(?P<pk>\d+)/$', adminapp.ProductActivateView.as_view(), name='product_activate'),

    # re_path('^user/create/$', adminapp.user_create, name='user_create'),
    # re_path('^users/read/$', adminapp.index, name='index'),
    # re_path('^user/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    # re_path('^user/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),
    # re_path('^user/activate/(?P<pk>\d+)/$', adminapp.user_activate, name='user_activate'),

    # re_path('^categories/$', adminapp.categories, name='categories'),
    # re_path('^category/create/$', adminapp.category_create, name='category_create'),
    # re_path('^category/update/(?P<pk>\d+)/$', adminapp.category_update, name='category_update'),
    # re_path('^category/delete/(?P<pk>\d+)/$', adminapp.category_delete, name='category_delete'),
    # re_path('^category/activate/(?P<pk>\d+)/$', adminapp.category_activate, name='category_activate'),

    # re_path('^products/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
    # re_path('^products/category/pk<int:pk>/$', adminapp.ProductListView.as_view(), name='products'),
    # re_path('^product/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    # re_path('^product/create/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    # re_path('^product/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    # re_path('^product/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
    # re_path('^product/activate/(?P<pk>\d+)/$', adminapp.product_activate, name='product_activate'),
]

geekshop/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.user_login, name='login'),
    re_path(r'^logout/$', authapp.user_logout, name='logout'),
    re_path(r'^register/$', authapp.user_register, name='register'),
    re_path(r'^edit/$', authapp.user_edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
# from geekshop import settings
from django.conf import settings
# from .settings import DEBUG

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='admin')),
    # path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.views.decorators.cache import cache_page

app_name = 'mainapp'

urlpatterns = [
    re_path('^$', mainapp.index, name='index'),
    re_path('^products/$', mainapp.products, name='products'),
    # re_path('^catalog/category/(?P<pk>\d+)/$', mainapp.products, name='catalog'),
    re_path('^catalog/category/(?P<pk>\d+)/$', cache_page(3600)(mainapp.products), name='catalog'),
    # re_path('^catalog/category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='catalog'),
    # re_path('^catalog/category/(None|[\d+])/page/(?P<page>\d+)/$', mainapp.products, name='catalog'),
    re_path('^catalog/category/(None|[\d+])/page/(?P<page>\d+)/$', cache_page(3600)(mainapp.products), name='catalog'),
    re_path('^catalog/product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path('^contacts/$', mainapp.contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/mainapp/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import get_object_or_404


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=128, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f'ProductCategory: {self.name} ({self.pk})'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        # return f'Product: {self.name} ({self.pk})'
        return f'{self.name} ({self.category.name})'

    def get_absolute_url(self):
        return reverse('admin:products',
                       kwargs={
                           'pk': self.category.pk,
                       })

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse

from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product

from adminapp.forms import AdminShopUserRegisterForm, AdminShopUserChangeForm, AdminProductCategoryEditForm, \
    AdminProductEditForm

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection

from django.db.models import F


# @user_passes_test(lambda x: x.is_superuser)
# def index(request):
#     object_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     context = {
#         'title': 'admin panel/users',
#         'object_list': object_list,
#     }
#     return render(request, 'adminapp/users.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class UsersListView(ListView):
    model = ShopUser

    # paginate_by = 2
    # template_name = 'adminapp/users.html'

    # @method_decorator(user_passes_test(lambda u: u.is_superuser))
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

    # def get_context_data(self, *, object_list=None, **kwargs):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'admin panel/users'
        return context


# def user_create(request):
#     if request.method == 'POST':
#         form = AdminShopUserRegisterForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin:index'))
#     else:
#         form = AdminShopUserRegisterForm()
#
#     context = {
#         'title': 'users/create',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/user_update.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class AdminShopUserCreateView(CreateView):
    model = ShopUser
    success_url = reverse_lazy('admin:index')
    form_class = AdminShopUserRegisterForm

    # template_name = 'adminapp/user_update.html'
    # fields = ('__all__')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'users/create'
        return context


# def user_update(request, pk):
#     edit_user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         form = AdminShopUserChangeForm(request.POST, request.FILES, instance=edit_user)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin:user_update',
#                                                 kwargs={
#                                                     'pk': edit_user.pk,
#                                                 }))
#     else:
#         form = AdminShopUserChangeForm(instance=edit_user)
#
#     content = {
#         'title': 'users/edit',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/user_update.html', content)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class AdminShopUserUpdateView(UpdateView):
    model = ShopUser
    success_url = reverse_lazy('admin:index')
    form_class = AdminShopUserChangeForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'users/edit'
        return context


# def user_delete(request, pk):
#     user = get_object_or_404(ShopUser, pk=pk)
#     # user.is_active = False
#     # user.save()
#     # return HttpResponseRedirect(reverse('admin:index'))
#     if request.method == 'POST':
#         # user.delete()
#         # вместо удаления лучше сделаем неактивным
#         user.is_active = False
#         user.save()
#         return HttpResponseRedirect(reverse('admin:index'))
#
#     context = {
#         'title': 'users/delete',
#         'user_to_delete': user,
#     }
#
#     return render(request, 'adminapp/user_delete.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class AdminShopUserDeleteView(DeleteView):
    model = ShopUser
    success_url = reverse_lazy('admin:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'users/delete'
        return context


# def user_activate(request, pk):
#     user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         user.is_active = True
#         user.save()
#         return HttpResponseRedirect(reverse('admin:index'))
#
#     context = {
#         'title': 'users/activate',
#         'user_to_activate': user,
#     }
#
#     return render(request, 'adminapp/user_activate.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class AdminShopUserActivateView(DeleteView):
    model = ShopUser
    success_url = reverse_lazy('admin:index')
    template_name_suffix = '_confirm_activate'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'users/activate'
        return context


# @user_passes_test(lambda x: x.is_superuser)
# def categories(request):
#     # categories_list = ProductCategory.objects.all()
#     categories_list = ProductCategory.objects.order_by('-is_active', 'name')
#
#     context = {
#         'title': 'admin panel/categories',
#         'object_list': categories_list,
#     }
#
#     return render(request, 'adminapp/categories.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCategoryListView(ListView):
    model = ProductCategory

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'admin panel/categories'
        return context


# def category_create(request):
#     if request.method == 'POST':
#         form = AdminProductCategoryEditForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin:categories'))
#     else:
#         form = AdminProductCategoryEditForm()
#
#     context = {
#         'title': 'categories/create',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/category_update.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    success_url = reverse_lazy('admin:categories')
    form_class = AdminProductCategoryEditForm

    # template_name = 'adminapp/category_update.html'
    # fields = ('__all__')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories/create'
        return context


# def category_update(request, pk):
#     edit_obj = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         form = AdminProductCategoryEditForm(request.POST, request.FILES, instance=edit_obj)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin:category_update',
#                                                 kwargs={
#                                                     'pk': edit_obj.pk,
#                                                 }))
#     else:
#         form = AdminProductCategoryEditForm(instance=edit_obj)
#
#     context = {
#         'title': 'categories/edit',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/category_update.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    success_url = reverse_lazy('admin:categories')
    form_class = AdminProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'categories/edit'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)


# def category_delete(request, pk):
#     item = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         item.is_active = False
#         item.product_set.all().update(is_active=False)
#         item.save()
#         return HttpResponseRedirect(reverse('admin:categories'))
#     else:
#         item.product_set.all().update(is_active=True)
#
#     context = {
#         'title': 'categories/delete',
#         # 'category_to_delete': item,
#         'object': item,
#     }
#
#     return render(request, 'adminapp/category_delete.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCategoryDeleteView(DeleteView):

geekshop/adminapp/templates/mainapp/product_confirm_activate.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="user_delete">
{#        Are you sure, if you want to activate <b>{{ product_to_activate.name }}</b>?#}
        Are you sure, if you want to activate <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="activate">
        </form>

{#        <a href="{% url 'admin:categories' %}" class="btn btn-success">cancel</a>#}
        <a href="{% url 'admin:products' object.category.pk %}" class="btn btn-success">cancel</a>
    </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/product_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="user_delete">
{#        Are you sure, if you want to delete <b>{{ product_to_delete.name }}</b>#}
        Are you sure, if you want to delete <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="delete">
        </form>

{#        <a href="{% url 'admin:categories' %}" class="btn btn-success">cancel</a>#}
        <a href="{% url 'admin:products' object.category.pk %}" class="btn btn-success">cancel</a>
    </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block container %}
    <div class="products_list">
{#		<img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">#}
		<img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
		<div class="product_name">
			{{ object.name|title }}
		</div>
		<div class="product_actions">
            <a href="{% url 'admin:product_update' object.pk %}" class="products_list-button btn btn-outline-secondary btn-sm">
                edit
            </a>
            {% if object.is_active %}
                <a href="{% url 'admin:product_delete' object.pk %}" class="products_list-button btn btn-outline-secondary btn-sm">
                    delete
                </a>
            {% else %}
                <a href="{% url 'admin:product_activate' object.pk %}" class="products_list-button btn btn-outline-secondary btn-sm">
                    activate
                </a>
            {% endif %}
		</div>
		<div class="summary">
			<b>price</b>
			<p>{{ object.price|local_currency }}</p>
			<b>quantity</b>
			<p>{{ object.quantity }}</p>
		</div>
		<div class="product_desc">
			<b>short description</b>
			<p>{{ object.short_desc }}</p>
		</div>
		<div class="product_desc">
			<b>description</b>
			<p>{{ object.description }}</p>
		</div>
	</div>
{% endblock %}

geekshop/adminapp/templates/mainapp/product_form.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="save">
        </form>
        <a href="{% url 'admin:categories' %}" class="form-control last btn btn-outline-secondary btn-sm">
            list of products
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/product_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block container %}
    <div class="products_list">
        <a href="{% url 'admin:product_create' category.pk %}" class="new_product products_list-button btn btn-outline-secondary btn-sm">
            new
        </a>
        <div class="paginator">
            {% if paginator.num_pages > 1 %}
                {% if page_obj.has_previous %}
                    <a href="{% url 'admin:products' category.pk page_obj.previous_page_number %}"><</a>
                {% endif %}
                <span class="current">
                page {{ page_obj.number }} from {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'admin:products' category.pk page_obj.next_page_number %}">></a>
                {% endif %}
            {% endif %}
        </div>
		{% for object in object_list %}
			<div class="product_record
                {% if not object.is_active %}
                    not_active
                {% endif %}">
{#				<img src="/media/{{ object.image|default:'product_images/default.jpg' }}" alt="{{ object.name }}">#}
				<img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
				<div class="product_name">
					{{ object.name|title }}
				</div>
				<div class="product_actions">
                    <a href="{% url 'admin:product_read' object.pk %}" class="products_list-button btn btn-outline-secondary btn-sm">
                        detailed
                    </a>
                    <a href="{% url 'admin:product_update' object.pk %}" class="products_list-button btn btn-outline-secondary btn-sm">
                        edit
                    </a>
                    {% if object.is_active %}
                        <a href="{% url 'admin:product_delete' object.pk %}" class="products_list-button btn btn-outline-secondary btn-sm">
                            delete
                        </a>
                    {% else %}
                        <a href="{% url 'admin:product_activate' object.pk %}" class="products_list-button btn btn-outline-secondary btn-sm">
                            activate
                        </a>
                    {% endif %}
				</div>
				<div class="summary">
					<b>price</b>
{#					<p>{{ object.price }} ₽</p>#}
					<p>{{ object.price|local_currency }}</p>
					<b>quantity</b>
					<p>{{ object.quantity }}</p>
				</div>
				<div class="product_desc">
					{{ object.short_desc|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

geekshop/adminapp/templates/mainapp/productcategory_confirm_activate.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="user_delete">
{#        Are you sure, if you want to activate <b>{{ category_to_activate.name }}</b>#}
        Are you sure, if you want to activate <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="activate">
        </form>

        <a href="{% url 'admin:categories' %}" class="btn btn-success">cancel</a>
    </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/productcategory_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="user_delete">
{#        Are you sure, if you want to delete <b>{{ category_to_delete.name }}</b>?#}
        Are you sure, if you want to delete <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="delete">
        </form>

        <a href="{% url 'admin:categories' %}" class="form-control last btn btn-success">cancel</a>
    </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/productcategory_form.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="save">
        </form>
        <a href="{% url 'admin:categories' %}" class="form-control last btn btn-outline-secondary btn-sm">
            list of categoties
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="categories_list">
        <a href="{% url 'admin:category_create' %}" class="new_category categories_list-button btn btn-outline-secondary btn-sm">
            new
        </a>

		{% for object in object_list %}
			<div class="category_record
                {% if not object.is_active %}
                    not_active
                {% endif %}">
				<div class="category_name">
					{{ object.name|title }}
				</div>
				<div class="category_actions">
                    <a href="{% url 'admin:products' object.pk %}" class="categories_list-button btn btn-outline-secondary btn-sm">
                        items of category
                    </a>
                    <br>
                    <a href="{% url 'admin:category_update' object.pk %}" class="categories_list-button btn btn-outline-secondary btn-sm">
                        edit
                    </a>
                    <br>
                    {% if object.is_active%}
                        <a href="{% url 'admin:category_delete' object.pk %}" class="categories_list-button btn btn-outline-secondary btn-sm">
                            delete
                        </a>
                    {% else %}
                        <a href="{% url 'admin:category_activate' object.pk %}" class="categories_list-button btn btn-outline-secondary btn-sm">
                            activate
                        </a>
                    {% endif %}
				</div>
				<div class="category_desc">
					{{ object.description|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}