geekshop/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.user_login, name='login'),
    re_path(r'^logout/$', authapp.user_logout, name='logout'),
    re_path(r'^register/$', authapp.user_register, name='register'),
    re_path(r'^edit/$', authapp.user_edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path, re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    re_path('^$', basketapp.index, name='index'),
    re_path('^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    re_path('^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    re_path('^edit/(?P<product_pk>\d+)/(?P<quantity>\d+)/ajax/$', basketapp.basket_edit),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
# from geekshop import settings
from django.conf import settings
# from .settings import DEBUG

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='admin')),
    # path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.views.decorators.cache import cache_page

app_name = 'mainapp'

urlpatterns = [
    re_path('^$', mainapp.index, name='index'),
    re_path('^products/$', mainapp.products, name='products'),
    # re_path('^catalog/category/(?P<pk>\d+)/$', mainapp.products, name='catalog'),
    re_path('^catalog/category/(?P<pk>\d+)/$', cache_page(3600)(mainapp.products), name='catalog'),
    # re_path('^catalog/category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='catalog'),
    # re_path('^catalog/category/(None|[\d+])/page/(?P<page>\d+)/$', mainapp.products, name='catalog'),
    re_path('^catalog/category/(None|[\d+])/page/(?P<page>\d+)/$', cache_page(3600)(mainapp.products), name='catalog'),
    re_path('^catalog/product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path('^contacts/$', mainapp.contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/media/mainapp/urls.py
# from django.contrib import admin
from django.urls import path, re_path
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),
    re_path(r'^products/$', mainapp.products, name='products'),
    re_path(r'^products/(\d+)/$', mainapp.products, name='category'),
    re_path(r'^product/$', mainapp.product, name='product'),
    re_path(r'^contacts/$', mainapp.contacts, name='contacts'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import get_object_or_404


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=128, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f'ProductCategory: {self.name} ({self.pk})'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        # return f'Product: {self.name} ({self.pk})'
        return f'{self.name} ({self.category.name})'

    def get_absolute_url(self):
        return reverse('admin:products',
                       kwargs={
                           'pk': self.category.pk,
                       })

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/media/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=128, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return f'ProductCategory: {self.name} ({self.pk})'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f'Product: {self.name} ({self.pk})'

geekshop/mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime
import json
import random
import os.path
from mainapp.models import ProductCategory, Product

from django.conf import settings
from django.core.cache import cache

from django.views.decorators.cache import cache_page

links_menu = [
    {'href': 'main:index', 'short_href': 'index', 'name': 'home'},
    {'href': 'main:products', 'short_href': 'products', 'name': 'products'},
    # {'href': 'main:history', 'short_href': 'history', 'name': 'history'},
    # {'href': 'main:showroom', 'short_href': 'showroom', 'name': 'showroom'},
    {'href': 'main:contacts', 'short_href': 'contacts', 'name': 'contact'},
]

# JSON_CONTACTS = "mainapp/json/contact_items.json"
JSON_PATH = "mainapp/json/"


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', errors='ignore') as infile:
        return json.load(infile)


def get_basket(user):
    if user.is_authenticated:
        return user.basket_set.all().order_by('product__category')
    else:
        return []


def get_hot_product():
    products = Product.objects.filter(is_active=True)
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True). \
                        exclude(pk=hot_product.pk)[:3]
    return same_products


def today():
    return datetime.date.today()


def index(request):
    # trending_products = Product.objects.filter(is_active=True)[:6]
    trending_products = get_products()[:6]
    # trending_products = Product.objects.filter(is_active=True, category__is_active=True)[:6]

    context = {
        'page_title': 'home',
        'today': today(),
        'links_menu': links_menu,
        # 'basket': get_basket(request.user),
        'trending_products': trending_products,
    }
    return render(request, 'mainapp/index.html', context)


@cache_page(3600)
def products(request, pk=None, page=1):
    categories = ProductCategory.objects.filter(is_active=True)
    hot_product = get_hot_product()

    if pk:
        if pk == '0':
            # products = Product.objects.filter(is_active=True).order_by('price')
            products = get_products_orederd_by_price()
        else:
            # products = Product.objects.filter(category__pk=pk, is_active=True).order_by('price')
            products = get_products_in_category_orederd_by_price(pk)
    else:
        # products = Product.objects.filter(is_active=True).order_by('price')
        products = get_products_orederd_by_price()

    products_paginator = Paginator(products, 2)
    try:
        products = products_paginator.get_page(page)
    except PageNotAnInteger:
        products = products_paginator.get_page(1)
    except EmptyPage:
        products = products_paginator.get_page(products_paginator.num_pages)

    # links_menu = get_links_menu()

    context = {
        'page_title': 'our products range',
        'today': today(),
        'links_menu': links_menu,
        'products': products,
        'categories': categories,
        # 'basket': get_basket(request.user),
        'hot_product': hot_product,
        'category_pk': pk,
    }
    return render(request, 'mainapp/products.html', context)


def product(request, pk=None):
    categories = ProductCategory.objects.filter(is_active=True)
    # product = get_object_or_404(Product, pk=pk)
    product = get_product(pk)
    same_products = get_same_products(product)

    context = {
        'page_title': 'product',
        'today': today(),
        'links_menu': links_menu,
        'product': product,
        'categories': categories,
        # 'basket': get_basket(request.user),
        'same_products': same_products,
    }
    return render(request, 'mainapp/product-details.html', context)


def contacts(request):
    # with open(JSON_CONTACTS, 'r', encoding='utf-8') as tmp_file:
    #     contact_items = json.load(tmp_file)

    # contact_items = load_from_json('contact_items')

    if settings.LOW_CACHE:
        key = f'contact_items'
        contact_items = cache.get(key)
        if contact_items is None:
            # contact_items = load_from_json('contacts__contact_items')
            contact_items = load_from_json('contact_items')
            cache.set(key, contact_items)
    else:
        # contact_items = load_from_json('contacts__contact_items')
        contact_items = load_from_json('contact_items')

    context = {
        'page_title': 'contact us',
        'contact_items': contact_items,
        'today': today(),
        'links_menu': links_menu,
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/contact.html', context)


# def get_links_menu():
#     if settings.LOW_CACHE:
#         key = 'links_menu'
#         links_menu = cache.get(key)
#         if links_menu is None:
#             links_menu = ProductCategory.objects.filter(is_active=True)
#             cache.set(key, links_menu)
#         return links_menu
#     else:
#         return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

geekshop/media/mainapp/views.py
from django.shortcuts import render
import datetime
import json
import csv
from mainapp.models import ProductCategory, Product

links_menu = [
    {'href': 'main:index', 'short_href': 'index', 'name': 'home'},
    {'href': 'main:products', 'short_href': 'products', 'name': 'products'},
    # {'href': 'main:history', 'short_href': 'history', 'name': 'history'},
    # {'href': 'main:showroom', 'short_href': 'showroom', 'name': 'showroom'},
    {'href': 'main:contacts', 'short_href': 'contacts', 'name': 'contact'},
]

categories = ProductCategory.objects.all()

CSV_PRODUCTCATEGORIES = "./csv/productcategories.csv"
CSV_PRODUCTS = "./csv/products.csv"


def today():
    return datetime.date.today()


def index(request):
    context = {
        'page_title': 'home',
        'today': today(),
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None):

    # import_categories(CSV_PRODUCTCATEGORIES)
    # import_products(CSV_PRODUCTS)

    products = Product.objects.all()
    category_name = 'all'
    if pk:
        for category in categories:
            if category.pk == int(pk):
                category_name = category.name
    context = {
        'page_title': 'our products range',
        'today': today(),
        'links_menu': links_menu,
        'products': products,
        'categories': categories,
        'category_name': category_name,
    }
    return render(request, 'mainapp/products.html', context)


def product(request):
    product = Product.objects.all()
    category_name = 'all'
    context = {
        'today': today(),
        'links_menu': links_menu,
        'product': product,
        'categories': categories,
        'category_name': category_name,
    }
    return render(request, 'mainapp/product-details.html', context)


def contacts(request):
    with open('json/contact_items.json', 'r', encoding='utf-8') as tmp_file:
        contact_items = json.load(tmp_file)

    context = {
        'page_title': 'contact us',
        'contact_items': contact_items,
        'today': today(),
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/contact.html', context)


def import_categories(csv_filename):
    data_reader = csv.reader(open(csv_filename), delimiter=',', quotechar='"')
    categories = [category.name for category in ProductCategory.objects.all()]
    for row in data_reader:
        if row[0] not in categories:
            category = ProductCategory()
            category.name = row[0]
            category.description = row[1]
            category.save()


def import_products(csv_filename):
    data_reader = csv.reader(open(csv_filename), delimiter=',', quotechar='"')
    products = [product.name for product in Product.objects.all()]
    for row in data_reader:
        if row[0] not in products:
            product = Product()
            product.category = ProductCategory.objects.get(id=int(row[0]))
            product.name = row[1]
            product.image = row[2]
            product.short_desc = row[3]
            product.description = row[4]
            product.price = float(row[5])
            product.quantity = int(row[6])
            product.save()

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <div class="title padding-site">

        {% include 'mainapp/includes/inc__main_menu.html' %}

        <div class="title">
            <h2 class="title-h2">Contact Us</h2>
        </div>
    </div>
    <main>
        <div class="contact padding-site">
            {% if contact_items %}
                {% for contact_item in contact_items %}
                    <div class="contact-item">
                    <div class="contact-text-block">
                        <div class="marker">
                            <i class="fas fa-map-marker-alt map-marker"></i>
                        </div>
                        <h2 class="contact-h3"><br>Office #{{ forloop.counter }}</h2><br>
                        <h2 class="contact-h3"><br>{{ contact_item.city }}</h2><br>
                        <p class="contact-text">Phone:<br>
                        <span class="contact-text-black">{{ contact_item.phone }}</span><br><br>
                        Email:<br>
                        <span class="contact-text-black">{{ contact_item.email }}</span><br><br>
                        Address:<br>
                        <span class="contact-text-light">{{ contact_item.address }}</span></p>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <h2 class="title-h2">Under Construction</h2>
            {% endif %}
        </div>
    </main>
{% endblock %}

geekshop/mainapp/templates/mainapp/product-details.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block container %}

    {% include 'mainapp/includes/inc__main_menu.html' %}

    <main>

        {% include 'mainapp/includes/inc__products_details_menu.html' %}

        {% if product %}
            <div class="desc padding-site">
                <div class="desc-slider">
{#                    <img src="/media/{{ product.image|default:'product_images/default.jpg' }}" class="desc-img" alt="slider1">#}
                    <img src="{{ product.image|media_folder_products }}" class="desc-img" alt="slider1">
                    <div class="pagination-desc">
                        <a href="#" class="pagination-desc-link">
{#                            <img src="/media/{{ product.image|default:'product_images/default.jpg' }}" class="pagination-desc-img" alt="controll">#}
                            <img src="{{ product.image|media_folder_products }}" class="pagination-desc-img" alt="controll">
                        </a>
                        <a href="#" class="pagination-desc-link">
{#                            <img src="/media/{{ product.image|default:'product_images/default.jpg' }}" class="pagination-desc-img pagination-desc-link-active" alt="controll">#}
                            <img src="{{ product.image|media_folder_products }}" class="pagination-desc-img" alt="controll">
                        </a>
                        <a href="#" class="pagination-desc-link">
{#                            <img src="/media/{{ product.image|default:'product_images/default.jpg' }}" class="pagination-desc-img" alt="controll">#}
                            <img src="{{ product.image|media_folder_products }}" class="pagination-desc-img" alt="controll">
                        </a>
                    </div>
                </div>
                <div class="desc-textblock">
                    <h2 class="desc-h2">{{ product.name | title }}</h2>
                    <h3 class="desc-h3">Hot Deal</h3>
{#                    <p class="desc-price">₽ <span class="desc-price-number">{{ product.price }}</span>/sq</p>#}
                    <p class="desc-price"><span class="desc-price-number">{{ product.price|local_currency }}</span>/sq</p>
                    <a href="{% url 'basket:add' product.pk %}"
                        class="desc-button">
                        Order Us
                    </a>
                    <p class="desc-text">
                        {{ product.short_desc | capfirst }}
                        <br><br>
                        {{ product.description | capfirst }}
                    </p>
                </div>
            </div>
        {% endif %}

        {% if same_products %}
            <div class="trending padding-site">
                <div class="trending-header">
                    <h2 class="trending-h2">Related Products</h2>
                    <a href="{% url 'main:products' %}" class="explore">Explore all</a>
                </div>
                <div class="trending-items">
                    {% for product in same_products %}
                        <a href="{% url 'main:product' product.pk %}" >
                            <img src="/media/{{ product.image }}" class="trending-item" alt="{{ product.short_desc }}">
                        </a>
                    {% endfor %}

                </div>
            </div>
        {% endif %}

    </main>


{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="title padding-site">

        {% include 'mainapp/includes/inc__main_menu.html' %}

        <div class="title">
            <h2 class="title-h2">Our Products Range</h2>
        </div>
    </div>
    <main>
        <div class="products padding-site">

            {% include 'mainapp/includes/inc__products_menu.html' %}

            <div class="trending-items">
                {% for product in products %}
                    <a href="{% url 'main:product' %}" >
                        <img src="/media/{{ product.image }}" class="trending-item" alt="trending-product-1">
{#                        <img src="{{ product.image.url }}" class="trending-item" alt="trending-product-1">#}
                    </a>
                {% endfor %}
            </div>
            <div class="sync">
                <i class="fas fa-sync"></i>
            </div>
        </div>
        <div class="exclusive">
            <div class="exclusive-item exclusive-item-1">
                <div class="exclusive-text-block">
                    <h3 class="exclusive-h3">Exclusive</h3>
                    <h2 class="exclusive-h2">Fishnet Chair</h2>
                    <p class="exclusive-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                    <a href="#" class="button">Order Us</a>
                </div>
            </div>
            <div class="exclusive-item exclusive-item-2">
                <div class="exclusive-text-block">
                    <h3 class="exclusive-h3">Exclusive</h3>
                    <h2 class="exclusive-h2">Fishnet Chair</h2>
                    <p class="exclusive-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
                    <a href="#" class="button">Order Us</a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block container %}
    <div class="title padding-site">

        {% include 'mainapp/includes/inc__main_menu.html' %}

        <div class="title">
            <h2 class="title-h2">Our Products Range</h2>
        </div>
    </div>
    <main>
        <div class="products padding-site">

            {% include 'mainapp/includes/inc__products_menu.html' %}
            <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'main:catalog' category_pk products.previous_page_number %}"><</a>
                {% endif %}
                <span class="current">
                page {{ products.number }} from {{ products.paginator.num_pages }}
                </span>
                {% if products.has_next %}
                    <a href="{% url 'main:catalog' category_pk products.next_page_number %}">></a>
{#                    <a href="{% url 'main:catalog' category_pk products.last %}">  >></a>#}
                {% endif %}
            </div>
            <div class="trending-items">
                {% for product in products %}
                    <a href="{% url 'main:product' product.pk %}" >
{#                        <img src="/media/{{ product.image|default:'product_images/default.jpg' }}" class="trending-item" alt="{{ product.short_desc }}">#}
                        <img src="{{ product.image|media_folder_products }}" class="trending-item" alt="{{ product.short_desc }}">
                    </a>
                {% endfor %}
            </div>
            <div class="sync">
                <i class="fas fa-sync"></i>
            </div>

        </div>

        {% if hot_product %}
            <div class="desc padding-site">
                <div class="desc-slider">
                    <a href="{% url 'main:product' hot_product.pk %}">
                        <img src="/media/{{ hot_product.image|default:'product_images/default.jpg' }}" class="desc-img" alt="slider1">
                    </a>
                </div>
                <div class="desc-textblock">
                    <h2 class="desc-h2">{{ hot_product.name | title }}</h2>
                    <h3 class="desc-h3">Hot Deal</h3>
{#                    <p class="desc-price">₽ <span class="desc-price-number">{{ hot_product.price }}</span>/sq</p>#}
                    <p class="desc-price"><span class="desc-price-number">{{ hot_product.price|local_currency }}</span>/sq</p>
                    <p class="desc-text">
                        {{ hot_product.short_desc | capfirst }}
                        <br><br>
                        {{ hot_product.description | capfirst }}
                    </p>
                </div>
            </div>
        {% endif %}

{#        <div class="exclusive">#}
{#            <div class="exclusive-item exclusive-item-1">#}
{#                <div class="exclusive-text-block">#}
{#                    <h3 class="exclusive-h3">Exclusive</h3>#}
{#                    <h2 class="exclusive-h2">Fishnet Chair</h2>#}
{#                    <p class="exclusive-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>#}
{#                    <a href="#" class="button">Order Us</a>#}
{#                </div>#}
{#            </div>#}
{#            <div class="exclusive-item exclusive-item-2">#}
{#                <div class="exclusive-text-block">#}
{#                    <h3 class="exclusive-h3">Exclusive</h3>#}
{#                    <h2 class="exclusive-h2">Fishnet Chair</h2>#}
{#                    <p class="exclusive-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>#}
{#                    <a href="#" class="button">Order Us</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
    </main>
{% endblock %}